#!/usr/bin/env python
# coding: utf-8

dudosos_comments = {
    "No tratan sobre ADPKD": ['no ADPKD', 'no ADPKD, datos exclusivamente animales', 'no ADPKD, datos exclusivamente animales', 'no ADPKD (aunque sí tratan PKD, pero causada por genes distintos a PKD1 y PKD2), datos exclusivamente animales', 'non ADPKD', 'no ADPKD (aunque sí estudian PKD, ARPKD)', 'no ADPKD (aunque sí PKD: riñón displásico multiquístico)', 'no ADPKD (aunque sí PKD: ARPKD), no biomarker', 'no ADPKD (pero sí ARTKD)', 'no ADPKD, no tengo claro si usan omics/bioinfo', 'no estudian ADPKD, no sé si usan datos humanos ni qué biomarcadores estudian', 'no ADPKD (revisan ARPKD), incluir si tengo pocos papers', 'no ADPKD, no sé si usan bioinfo/ómicas', 'no ADPKD (diabetic nephropathy)', 'no ADPKD (ARPKD), pero puedo incluirlo si me quedo corto', 'no ADPKD, aunque la propuesta es interesante', 'no ADPKD, aunque buena propuesta (tener en cuenta si voy corto)'],
    
    "Tienen un subgrupo de pacientes ADPKD (o pueden tenerlo), pero no queda clara su aportación": ['no sé (aunque supongo) si hay pacientes ADPKD. Se trata de un GWAS, por lo que los marcadores son génicos, aunque no sé cuáles ni su traslacionalidad', 'necesito profundizar en su aportación a ADPKD para decidir', 'averiguar si hay pacientes con CKD que sean ADPKD', 'no sé si incluye pacientes ADPKD, no sé qué datos usan, se habla de marcadores alternativos pero tengo dudas de qué estudian', 'revisar qué hallan para ADPKD y sus referencias', 'no sé si ADPKD, ni qué biomarkers... profundizar para decidir', 'no sé si ADPKD, ni qué biomarkers... profundizar para decidir', 'mencionan ADPKD, pero no sé si lo estudian --> profundizar en ello para decidir', 'profundizar: hay datos de ADPKD? qué aportan como biomarker?', 'profundizar: hay ADPKD? qué biomarkers ven en ellos?', 'profundizar: hay ADPKD? (creo que es un motivo de exclusión) si los hay, que aportan como biomarker?', 'necesito profundizar para ver si aportan a ADPKD y qué biomarcadores', 'necesito profundizar en si contribuyen algo a ADPKD para decidir', 'profundizar en aportación a ADPKD para decidir', 'profundizar: se aplica a pacientes con ADPKD? cuál es su aporte específico como biomarker?', 'profundizar: incluyen ADPKD? si es así, concluyen algo sobre ella?', 'no sé si estudian algo relacionado a ADPKD (aunque sea en una sección) o solo la mencionan --> profundizar en ello y ver si aportan algo para decidir', 'no sé si estudian algo en concreto de ADPKD... creo que solo buscan variantes de ADTKD... profundizar más para confirmar', 'no sé qué biomarcadores estudian, ni si profundizan en ADPKD... profundizar mejor en el estudio para decidir', 'no sé si ADPKD, falta profundizar en biomarkers... profundizar para incluir/descartar', 'no sé si ADPKD, no sé qué biomarkers usan, no sé si usan omcias/bioinfo... profundizar más',  'no sé si ADPKD, no sé qué biomarkers estudian, no sé si usan bioinfo... profundizar para decidir'], 
    
    "No usan datos humanos (o no queda claro su uso en el abstract)": ['datos exclusivamente animales', 'non-human study', 'datos exclusivamente animales, lo incluiría si me faltasen papers', 'comprobar si usan datos humanos para incluir o no'], 
    
    "Aportación poco clara en cuanto a biomarcadores": ['no sé si hay biomarcadores, ni cuales son', 'me falta saber más sobre los biomarkers y sobre qué datos utilizan', 'no sé si hay biomarkers... profundizar para decidir', 'no sé qué biomarker aportan... profundizar para decidir', 'profundizar: cuál es el aporte en biomarker?', 'necesito profundizar en su aporte como biomarker', 'necesito profundizar ya que no estoy seguro de contribución en biomarkers'], 

    "Repasar": ['profundizar en qué aportan a ADPKD (abstract menciona a SNPS) para decidir', 'profundizar en qué técnicas usan para decidir', 'no sé si usan ómicas/bioinfo... profundizar para decidir', 'necesito profundizar en si usan omics/bioinfo', 'necesito profundizar en si utilizan omicas/bioinfo']
}
